site_name: My Docs
nav:
  - Home: index.md
  - Visão do Produto e Projeto: visao_do_produto.md
  - Documento de requisitos: documento_de_requisitos.md
  - Entregas: entregas.md
  - Sprint Planning: sprint_planning.md
  - Sprint Retrospective: sprint_retrospective.md
  
