site_name: My Docs
nav:
  - Home: index.md
  - Visão do Produto e Projeto: visao_do_produto.md
  - Documento de requisitos: documento_de_requisitos.md
  - Entregas: entregas.md
  - Sprint Planning: sprint_planning.md
  - Sprint Retrospective: sprint_retrospective.md
  - Caso de uso Adicionar Exercício: AdicionarExercícios.md
  - Caso de uso Adicionar Pendência: AdicionarPendencia.md
  - Caso de uso Visualizar Alunos: VisualizarAlunos.md
  - Caso de uso Manter Aluno: ManterAluno.md
  - Caso de uso Enviar Treino: EnviarTreino.md
  
